#include "FileFormats/JVM/Instruction.hpp"

#include "../Util/Macros.hpp"


#include <map>
#include <tuple>
#include <cassert>

using namespace FileFormats;
using namespace JVM;

using namespace std::literals;

static std::map<U8, std::string_view> OpCodeNames
{
  //copy paste is faster than writing some fancy macro
  NAMED_TUPLE(NOP           ), 
  NAMED_TUPLE(ACONST_NULL   ), 
  NAMED_TUPLE(ICONST_M1     ), 
  NAMED_TUPLE(ICONST_0      ), 
  NAMED_TUPLE(ICONST_1      ), 
  NAMED_TUPLE(ICONST_2      ), 
  NAMED_TUPLE(ICONST_3      ), 
  NAMED_TUPLE(ICONST_4      ), 
  NAMED_TUPLE(ICONST_5      ), 
  NAMED_TUPLE(LCONST_0      ), 
  NAMED_TUPLE(LCONST_1      ), 
  NAMED_TUPLE(FCONST_0      ), 
  NAMED_TUPLE(FCONST_1      ), 
  NAMED_TUPLE(FCONST_2      ), 
  NAMED_TUPLE(DCONST_0      ), 
  NAMED_TUPLE(DCONST_1      ), 
  NAMED_TUPLE(BIPUSH        ), 
  NAMED_TUPLE(SIPUSH        ), 
  NAMED_TUPLE(LDC           ), 
  NAMED_TUPLE(LDC_W         ), 
  NAMED_TUPLE(LDC2_W        ), 
  NAMED_TUPLE(ILOAD         ), 
  NAMED_TUPLE(LLOAD         ), 
  NAMED_TUPLE(FLOAD         ), 
  NAMED_TUPLE(DLOAD         ), 
  NAMED_TUPLE(ALOAD         ), 
  NAMED_TUPLE(ILOAD_0       ), 
  NAMED_TUPLE(ILOAD_1       ), 
  NAMED_TUPLE(ILOAD_2       ), 
  NAMED_TUPLE(ILOAD_3       ), 
  NAMED_TUPLE(LLOAD_0       ), 
  NAMED_TUPLE(LLOAD_1       ), 
  NAMED_TUPLE(LLOAD_2       ), 
  NAMED_TUPLE(LLOAD_3       ), 
  NAMED_TUPLE(FLOAD_0       ), 
  NAMED_TUPLE(FLOAD_1       ), 
  NAMED_TUPLE(FLOAD_2       ), 
  NAMED_TUPLE(FLOAD_3       ), 
  NAMED_TUPLE(DLOAD_0       ), 
  NAMED_TUPLE(DLOAD_1       ), 
  NAMED_TUPLE(DLOAD_2       ), 
  NAMED_TUPLE(DLOAD_3       ), 
  NAMED_TUPLE(ALOAD_0       ), 
  NAMED_TUPLE(ALOAD_1       ), 
  NAMED_TUPLE(ALOAD_2       ), 
  NAMED_TUPLE(ALOAD_3       ), 
  NAMED_TUPLE(IALOAD        ), 
  NAMED_TUPLE(LALOAD        ), 
  NAMED_TUPLE(FALOAD        ), 
  NAMED_TUPLE(DALOAD        ), 
  NAMED_TUPLE(AALOAD        ), 
  NAMED_TUPLE(BALOAD        ), 
  NAMED_TUPLE(CALOAD        ), 
  NAMED_TUPLE(SALOAD        ), 
  NAMED_TUPLE(ISTORE        ), 
  NAMED_TUPLE(LSTORE        ), 
  NAMED_TUPLE(FSTORE        ), 
  NAMED_TUPLE(DSTORE        ), 
  NAMED_TUPLE(ASTORE        ), 
  NAMED_TUPLE(ISTORE_0      ), 
  NAMED_TUPLE(ISTORE_1      ), 
  NAMED_TUPLE(ISTORE_2      ), 
  NAMED_TUPLE(ISTORE_3      ), 
  NAMED_TUPLE(LSTORE_0      ), 
  NAMED_TUPLE(LSTORE_1      ), 
  NAMED_TUPLE(LSTORE_2      ), 
  NAMED_TUPLE(LSTORE_3      ), 
  NAMED_TUPLE(FSTORE_0      ), 
  NAMED_TUPLE(FSTORE_1      ), 
  NAMED_TUPLE(FSTORE_2      ), 
  NAMED_TUPLE(FSTORE_3      ), 
  NAMED_TUPLE(DSTORE_0      ), 
  NAMED_TUPLE(DSTORE_1      ), 
  NAMED_TUPLE(DSTORE_2      ), 
  NAMED_TUPLE(DSTORE_3      ), 
  NAMED_TUPLE(ASTORE_0      ), 
  NAMED_TUPLE(ASTORE_1      ), 
  NAMED_TUPLE(ASTORE_2      ), 
  NAMED_TUPLE(ASTORE_3      ), 
  NAMED_TUPLE(IASTORE       ), 
  NAMED_TUPLE(LASTORE       ), 
  NAMED_TUPLE(FASTORE       ), 
  NAMED_TUPLE(DASTORE       ), 
  NAMED_TUPLE(AASTORE       ), 
  NAMED_TUPLE(BASTORE       ), 
  NAMED_TUPLE(CASTORE       ), 
  NAMED_TUPLE(SASTORE       ), 
  NAMED_TUPLE(POP           ), 
  NAMED_TUPLE(POP2          ), 
  NAMED_TUPLE(DUP           ), 
  NAMED_TUPLE(DUP_X1        ), 
  NAMED_TUPLE(DUP_X2        ), 
  NAMED_TUPLE(DUP2          ), 
  NAMED_TUPLE(DUP2_X1       ), 
  NAMED_TUPLE(DUP2_X2       ), 
  NAMED_TUPLE(SWAP          ), 
  NAMED_TUPLE(IADD          ), 
  NAMED_TUPLE(LADD          ), 
  NAMED_TUPLE(FADD          ), 
  NAMED_TUPLE(DADD          ), 
  NAMED_TUPLE(ISUB          ), 
  NAMED_TUPLE(LSUB          ), 
  NAMED_TUPLE(FSUB          ), 
  NAMED_TUPLE(DSUB          ), 
  NAMED_TUPLE(IMUL          ), 
  NAMED_TUPLE(LMUL          ), 
  NAMED_TUPLE(FMUL          ), 
  NAMED_TUPLE(DMUL          ), 
  NAMED_TUPLE(IDIV          ), 
  NAMED_TUPLE(LDIV          ), 
  NAMED_TUPLE(FDIV          ), 
  NAMED_TUPLE(DDIV          ), 
  NAMED_TUPLE(IREM          ), 
  NAMED_TUPLE(LREM          ), 
  NAMED_TUPLE(FREM          ), 
  NAMED_TUPLE(DREM          ), 
  NAMED_TUPLE(INEG          ), 
  NAMED_TUPLE(LNEG          ), 
  NAMED_TUPLE(FNEG          ), 
  NAMED_TUPLE(DNEG          ), 
  NAMED_TUPLE(ISHL          ), 
  NAMED_TUPLE(LSHL          ), 
  NAMED_TUPLE(ISHR          ), 
  NAMED_TUPLE(LSHR          ), 
  NAMED_TUPLE(IUSHR         ), 
  NAMED_TUPLE(LUSHR         ), 
  NAMED_TUPLE(IAND          ), 
  NAMED_TUPLE(LAND          ), 
  NAMED_TUPLE(IOR           ), 
  NAMED_TUPLE(LOR           ), 
  NAMED_TUPLE(IXOR          ), 
  NAMED_TUPLE(LXOR          ), 
  NAMED_TUPLE(IINC          ), 
  NAMED_TUPLE(I2L           ), 
  NAMED_TUPLE(I2F           ), 
  NAMED_TUPLE(I2D           ), 
  NAMED_TUPLE(L2I           ), 
  NAMED_TUPLE(L2F           ), 
  NAMED_TUPLE(L2D           ), 
  NAMED_TUPLE(F2I           ), 
  NAMED_TUPLE(F2L           ), 
  NAMED_TUPLE(F2D           ), 
  NAMED_TUPLE(D2I           ), 
  NAMED_TUPLE(D2L           ), 
  NAMED_TUPLE(D2F           ), 
  NAMED_TUPLE(I2B           ), 
  NAMED_TUPLE(I2C           ), 
  NAMED_TUPLE(I2S           ), 
  NAMED_TUPLE(LCMP          ), 
  NAMED_TUPLE(FCMPL         ), 
  NAMED_TUPLE(FCMPG         ), 
  NAMED_TUPLE(DCMPL         ), 
  NAMED_TUPLE(DCMPG         ), 
  NAMED_TUPLE(IFEQ          ), 
  NAMED_TUPLE(IFNE          ), 
  NAMED_TUPLE(IFLT          ), 
  NAMED_TUPLE(IFGE          ), 
  NAMED_TUPLE(IFGT          ), 
  NAMED_TUPLE(IFLE          ), 
  NAMED_TUPLE(IF_ICMPEQ     ), 
  NAMED_TUPLE(IF_ICMPNE     ), 
  NAMED_TUPLE(IF_ICMPLT     ), 
  NAMED_TUPLE(IF_ICMPGE     ), 
  NAMED_TUPLE(IF_ICMPGT     ), 
  NAMED_TUPLE(IF_ICMPLE     ), 
  NAMED_TUPLE(IF_ACMPEQ     ), 
  NAMED_TUPLE(IF_ACMPNE     ), 
  NAMED_TUPLE(GOTO          ), 
  NAMED_TUPLE(JSR           ), 
  NAMED_TUPLE(RET           ), 
  NAMED_TUPLE(TABLESWITCH   ), 
  NAMED_TUPLE(LOOKUPSWITCH  ), 
  NAMED_TUPLE(IRETURN       ), 
  NAMED_TUPLE(LRETURN       ), 
  NAMED_TUPLE(FRETURN       ), 
  NAMED_TUPLE(DRETURN       ), 
  NAMED_TUPLE(ARETURN       ), 
  NAMED_TUPLE(RETURN        ), 
  NAMED_TUPLE(GETSTATIC     ), 
  NAMED_TUPLE(PUTSTATIC     ), 
  NAMED_TUPLE(GETFIELD      ), 
  NAMED_TUPLE(PUTFIELD      ), 
  NAMED_TUPLE(INVOKEVIRTUAL ), 
  NAMED_TUPLE(INVOKESPECIAL ), 
  NAMED_TUPLE(INVOKESTATIC  ), 
  NAMED_TUPLE(INVOKEINTERFACE),
  NAMED_TUPLE(INVOKEDYNAMIC ), 
  NAMED_TUPLE(NEW           ), 
  NAMED_TUPLE(NEWARRAY      ), 
  NAMED_TUPLE(ANEWARRAY     ), 
  NAMED_TUPLE(ARRAYLENGTH   ), 
  NAMED_TUPLE(ATHROW        ), 
  NAMED_TUPLE(CHECKCAST     ), 
  NAMED_TUPLE(INSTANCEOF    ), 
  NAMED_TUPLE(MONITORENTER  ), 
  NAMED_TUPLE(MONITOREXIT   ), 
  NAMED_TUPLE(WIDE          ), 
  NAMED_TUPLE(MULTIANEWARRAY), 
  NAMED_TUPLE(IFNULL        ), 
  NAMED_TUPLE(IFNONNULL     ), 
  NAMED_TUPLE(GOTO_W        ), 
  NAMED_TUPLE(JSR_W         ), 
  NAMED_TUPLE(BREAKPOINT    ), 
  NAMED_TUPLE(IMPDEP1       ), 
  NAMED_TUPLE(IMPDEP2       ), 
};

ErrorOr<std::string_view> FileFormats::JVM::GetOpCodeMnemonic(U8 opCode)
{
  auto itr = OpCodeNames.find(opCode);

  if(itr != OpCodeNames.end())
    return std::get<1>(*itr);

  return Error::FromFormatStr("unknown name for opcode: %#04x", opCode);
}

ErrorOr<std::string_view> Instruction::GetMnemonic() const
{
  return GetOpCodeMnemonic(this->OpCode);
}

size_t Instruction::GetLength() const
{
  return 1 + OperandBytes.size();
}
